services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-monitor-app
    privileged: true
    restart: always
    working_dir: /var/www
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./:/var/www
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./database:/var/www/database
      - /proc:/proc:ro
      - /sys:/sys:ro
    networks:
      - hellojonathan-network

  nginx:
    image: nginx:alpine
    container_name: server-monitor-nginx
    restart: always
    ports:
      - "8081:80" # Langsung buka port 80 agar bisa diakses via IP Mini PC
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - hellojonathan-network
    depends_on:
      - app

  # tunnel:
  #   image: cloudflare/cloudflared:latest
  #   container_name: server-monitor-tunnel
  #   restart: always
  #   # Ganti YOUR_TOKEN_HERE dengan token asli dari dashboard Cloudflare Anda
  #   command: tunnel --no-autoupdate run --token eyJhIjoiZGY4NTRiZGMxMDRhOWQ0MGFhMDUxZTdmMmQwOGE1ZWQiLCJ0IjoiYjFmNGFkYzgtNWE4Zi00NWYyLWE2YTEtNjk3OTIwMGVlZjcxIiwicyI6Ik5EQTFaR05qWkRjdE5EUmhOaTAwWmprM0xUaGtOemt0T1RsaE1EUmtZamRsTVRFMyJ9
  #   networks:
  #     - hellojonathan-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-monitor-worker
    restart: always
    command: php artisan queue:work --tries=3
    volumes:
      - ./:/var/www
    networks:
      - hellojonathan-network
    depends_on:
      - app

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-monitor-scheduler
    restart: always
    command: sh -c "while [ true ]; do php artisan schedule:run --no-interaction & sleep 60; done"
    volumes:
      - ./:/var/www
    networks:
      - hellojonathan-network
    depends_on:
      - app

networks:
  hellojonathan-network:
    external: true
    name: hellojonathan-network
